version: "1.0.{build}"

environment:
  COVERALLS_REPO_TOKEN:
    secure: XtSPDpsl8BDGzGlBpr9jIzBLKaBmC5MyKvU2HRf/7jKTeug9n06ae8MAKHLDsJBS

before_build:

- ps: >-

    cd ScreenCapture



    nuget restore



    cd C:\projects\ScreenCapture

build:

  project: ScreenCapture\ScreenCapture.sln

  verbosity: minimal

after_test:

- cmd: >-

    ScreenCapture\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:ScreenCapture\ScreenCaptureTesting\bin\Debug/ScreenCaptureTesting.dll" -output:coverage.xml



    ScreenCapture\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml