version: "{build}"

skip_tags: true

configuration: Debug

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_REPO_TOKEN:
    secure: XtSPDpsl8BDGzGlBpr9jIzBLKaBmC5MyKvU2HRf/7jKTeug9n06ae8MAKHLDsJBS

nuget:
  disable_publish_on_pr: true

install:
  - nuget restore

build:
  project: ScreenCapture\ScreenCapture.sln
  verbosity: minimal

  after_test:
# generate report for NUnit testing framework:
    #-cmd: ScreenCapture\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single YOURPROJECT.Tests\bin\debug\YOURPROJECT.Tests.dll" -output:coverage.xml

# generate report for MSTest testing framework:
    #-cmd: ScreenCapture\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:ScreenCapture.Tests/bin/debug/ScreenCapture.Tests.dll" -output:coverage.xml
    #-cmd: ScreenCapture\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml