version: {build}

skip_tags: true

configuration: Debug

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_REPO_TOKEN:
    secure: XtSPDpsl8BDGzGlBpr9jIzBLKaBmC5MyKvU2HRf/7jKTeug9n06ae8MAKHLDsJBS

nuget:
  disable_publish_on_pr: true

install:
  - nuget restore

build:
  project: ./ScreenCapture/ScreenCapture.sln
  verbosity: minimal